name: workflow-docker-manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
  call-reusable-workflow:
    uses: binhex/workflow-templates/.github/workflows/workflow-docker-manual.yml@main
    with:
      tags: ${{ github.event.inputs.tags }}
