name: workflow-docker-release

on:
  push:
    tags:
      - '*'

jobs:
  call-reusable-workflow:
    uses: binhex/workflow-templates/.github/workflows/workflow-docker-release.yml@main
    with:
      tags: ${{ github.event.inputs.tags }}
